
Detailed parameter count:
  total                  | Total:   52,149,504 | Trainable:    8,207,616
  token_embeddings       | Total:    2,451,456 | Trainable:    2,451,456
  position_embeddings    | Total:            0 | Trainable:            0
  attention_layers       | Total:    7,520,256 | Trainable:    2,211,840
  feed_forward_layers    | Total:    3,538,944 | Trainable:    3,538,944
  layer_norms            | Total:        4,608 | Trainable:        4,608
  final_layer_norm       | Total:          768 | Trainable:          768
  language_model_head    | Total:   38,633,472 | Trainable:            0
------------------------------------------------------------
step 0: train loss 10.9702, val loss 10.9694
iter 0: loss 10.9740, lr 0.00005, time 6880.74ms, mfu -100.00%
iter 10: loss 9.6101, lr 0.00055, time 519.63ms, mfu 35.56%
iter 20: loss 9.4772, lr 0.00104, time 521.46ms, mfu 35.55%
iter 30: loss 9.2562, lr 0.00154, time 528.89ms, mfu 35.49%
iter 40: loss 9.2410, lr 0.00204, time 537.64ms, mfu 35.38%
iter 50: loss 8.9850, lr 0.00254, time 539.54ms, mfu 35.27%
iter 60: loss 8.8902, lr 0.00303, time 544.69ms, mfu 35.13%
iter 70: loss 8.8366, lr 0.00353, time 541.89ms, mfu 35.03%
iter 80: loss 8.6251, lr 0.00403, time 555.07ms, mfu 34.86%
iter 90: loss 8.6760, lr 0.00453, time 555.86ms, mfu 34.70%
step 100: train loss 8.5492, val loss 8.5822
saving checkpoint to out

=== SCALING OPERATION TRIGGERED (DDP SYNC) ===
Operation: merge_lora_weights
Trigger reason: Timeout
Current val loss: 8.5822, Trigger loss: 1.0000
Iterations since last op: 100, Max wait: 100
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/nanoGPT/train.py", line 620, in <module>
    operation_succeeded = execute_operation(next_op, trigger_reason, current_val_loss, iter_num)
  File "/teamspace/studios/this_studio/nanoGPT/train.py", line 349, in execute_operation
    op_desc = op['desc']  if op['desc'] is not None else ''
KeyError: 'desc'
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/nanoGPT/train.py", line 620, in <module>
    operation_succeeded = execute_operation(next_op, trigger_reason, current_val_loss, iter_num)
  File "/teamspace/studios/this_studio/nanoGPT/train.py", line 349, in execute_operation
    op_desc = op['desc']  if op['desc'] is not None else ''
KeyError: 'desc'
